package com.example.batch.demo.mybatis.mapper;

import com.example.batch.demo.mybatis.entity.Meteorology;
import com.example.batch.demo.mybatis.entity.MeteorologyExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MeteorologyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    long countByExample(MeteorologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int deleteByExample(MeteorologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int insert(Meteorology row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int insertSelective(Meteorology row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    List<Meteorology> selectByExample(MeteorologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    Meteorology selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Meteorology row, @Param("example") MeteorologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Meteorology row, @Param("example") MeteorologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Meteorology row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Meteorology row);
}