package com.example.batch.demo.mybatis.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   気象
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table meteorology
 */
public class Meteorology implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   都道府県
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.prefecture
     *
     * @mbg.generated
     */
    private String prefecture;

    /**
     * Database Column Remarks:
     *   測定日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.measure_date
     *
     * @mbg.generated
     */
    private LocalDate measureDate;

    /**
     * Database Column Remarks:
     *   最高気温
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.heighest_temperature
     *
     * @mbg.generated
     */
    private Float heighestTemperature;

    /**
     * Database Column Remarks:
     *   最低気温
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.lowest_temperature
     *
     * @mbg.generated
     */
    private Float lowestTemperature;

    /**
     * Database Column Remarks:
     *   平均気温
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.average_temperature
     *
     * @mbg.generated
     */
    private Float averageTemperature;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * Database Column Remarks:
     *   削除日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.deleted_at
     *
     * @mbg.generated
     */
    private LocalDateTime deletedAt;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorology.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.id
     *
     * @return the value of meteorology.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.id
     *
     * @param id the value for meteorology.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.prefecture
     *
     * @return the value of meteorology.prefecture
     *
     * @mbg.generated
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.prefecture
     *
     * @param prefecture the value for meteorology.prefecture
     *
     * @mbg.generated
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture == null ? null : prefecture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.measure_date
     *
     * @return the value of meteorology.measure_date
     *
     * @mbg.generated
     */
    public LocalDate getMeasureDate() {
        return measureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.measure_date
     *
     * @param measureDate the value for meteorology.measure_date
     *
     * @mbg.generated
     */
    public void setMeasureDate(LocalDate measureDate) {
        this.measureDate = measureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.heighest_temperature
     *
     * @return the value of meteorology.heighest_temperature
     *
     * @mbg.generated
     */
    public Float getHeighestTemperature() {
        return heighestTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.heighest_temperature
     *
     * @param heighestTemperature the value for meteorology.heighest_temperature
     *
     * @mbg.generated
     */
    public void setHeighestTemperature(Float heighestTemperature) {
        this.heighestTemperature = heighestTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.lowest_temperature
     *
     * @return the value of meteorology.lowest_temperature
     *
     * @mbg.generated
     */
    public Float getLowestTemperature() {
        return lowestTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.lowest_temperature
     *
     * @param lowestTemperature the value for meteorology.lowest_temperature
     *
     * @mbg.generated
     */
    public void setLowestTemperature(Float lowestTemperature) {
        this.lowestTemperature = lowestTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.average_temperature
     *
     * @return the value of meteorology.average_temperature
     *
     * @mbg.generated
     */
    public Float getAverageTemperature() {
        return averageTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.average_temperature
     *
     * @param averageTemperature the value for meteorology.average_temperature
     *
     * @mbg.generated
     */
    public void setAverageTemperature(Float averageTemperature) {
        this.averageTemperature = averageTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.created_at
     *
     * @return the value of meteorology.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.created_at
     *
     * @param createdAt the value for meteorology.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.updated_at
     *
     * @return the value of meteorology.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.updated_at
     *
     * @param updatedAt the value for meteorology.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.deleted_at
     *
     * @return the value of meteorology.deleted_at
     *
     * @mbg.generated
     */
    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.deleted_at
     *
     * @param deletedAt the value for meteorology.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorology.delete_flag
     *
     * @return the value of meteorology.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorology.delete_flag
     *
     * @param deleteFlag the value for meteorology.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Meteorology other = (Meteorology) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPrefecture() == null ? other.getPrefecture() == null : this.getPrefecture().equals(other.getPrefecture()))
            && (this.getMeasureDate() == null ? other.getMeasureDate() == null : this.getMeasureDate().equals(other.getMeasureDate()))
            && (this.getHeighestTemperature() == null ? other.getHeighestTemperature() == null : this.getHeighestTemperature().equals(other.getHeighestTemperature()))
            && (this.getLowestTemperature() == null ? other.getLowestTemperature() == null : this.getLowestTemperature().equals(other.getLowestTemperature()))
            && (this.getAverageTemperature() == null ? other.getAverageTemperature() == null : this.getAverageTemperature().equals(other.getAverageTemperature()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()))
            && (this.getDeletedAt() == null ? other.getDeletedAt() == null : this.getDeletedAt().equals(other.getDeletedAt()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPrefecture() == null) ? 0 : getPrefecture().hashCode());
        result = prime * result + ((getMeasureDate() == null) ? 0 : getMeasureDate().hashCode());
        result = prime * result + ((getHeighestTemperature() == null) ? 0 : getHeighestTemperature().hashCode());
        result = prime * result + ((getLowestTemperature() == null) ? 0 : getLowestTemperature().hashCode());
        result = prime * result + ((getAverageTemperature() == null) ? 0 : getAverageTemperature().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        result = prime * result + ((getDeletedAt() == null) ? 0 : getDeletedAt().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorology
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prefecture=").append(prefecture);
        sb.append(", measureDate=").append(measureDate);
        sb.append(", heighestTemperature=").append(heighestTemperature);
        sb.append(", lowestTemperature=").append(lowestTemperature);
        sb.append(", averageTemperature=").append(averageTemperature);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}