name: spring-batch-demo
services:
  mysql:
    build: .
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306

  app:
    image: mcr.microsoft.com/devcontainers/java:21-bookworm
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../:/workspace

volumes:
  data: